sudo: required
language: bash
services:
  - docker
before_script:
  - export APP_IMAGE=keboola-component
  - docker -v
  - docker build -t $APP_IMAGE .
  - docker run $APP_IMAGE /code/tests/run.sh
script: 
  - skip
deploy:
  provider: script
  skip_cleanup: true
  script: ./deploy.sh
  on:
    tags: true